# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "ubuntu-20.04"
  config.vm.network :private_network, ip: "192.168.56.20"
  config.vm.provider :virtualbox do |vb|
    vb.name = "ubuntu-20.04"
    vb.cpus = 1
    vb.memory = "1024"
  end
  config.ssh.insert_key = false
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/ansible.yml"
    ansible.inventory_path = "provisioning/hosts"
    ansible.limit = 'all'
  end
end
