- name: my ansible start
  hosts: vagrant
  gather_facts: no
  become: yes
  pre_tasks:
    - name: set locale
      shell: localectl set-locale LANG=ja_JP.utf8
    - name: set timezone to Asia/Tokyo
      timezone:
        name: Asia/Tokyo
  tasks:
    - name: apt update
      apt: update_cache=yes
    - name: install package
      apt:
        name:
          - git
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    - name: curl shell
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    - name: echo shell
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: apt update
      apt: update_cache=yes
    - name: install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
